### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by josegonzalez** [heroku/heroku-buildpack-multi#19]
The only real change is the logging output, which is actually a nice change :)

**Comment by edmorley** [comment]
Hi! Sure happy to :-)

For most buildpacks the tag is created at the time they are pushed to the buildpack registry, but since this buildpack isn't on the registry, that didn't occur. (Most people using the GitHub URLs on the platform will use the default branch.)

I've tagged current `master` as `v1.0.1`, given (a) the previous tag was `v1.0.0` (most other buildpacks use integer versioning instead), (b) with the various reverts the only change is logging/readme/licence, so a patch bump only seems appropriate semver wise:
https://github.com/heroku/heroku-buildpack-multi/compare/v1.0.0...v1.0.1

**Comment by josegonzalez** [comment]
<3 Thanks it is definitely appreciated :)
