### ISSUE TITLE
what is the name of this buildpack in heroku buildpack registry ?

### ISSUE THREAD

**Issue by haliliceylan** [heroku/heroku-buildpack-multi#22]
![image](https://user-images.githubusercontent.com/33789758/111775366-b7e16600-88c1-11eb-9faf-c0bdc6916f4a.png)
i did not get the buildpack name of this repo, its showing on heroku buildpack list
see: https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-multi

but i can not found repo on heroku cli. i need this name for generate this url;
http://buildpack-registry.s3.amazonaws.com/heroku/heroku-buildpack-multi.tgz

**Comment by edmorley** [comment]
@haliliceylan Hi! The Heroku Buildpack Registry and https://elements.heroku.com are unfortunately two independent things. Buildpacks automatically show up at  https://elements.heroku.com based on usage, however buildpacks only end up in the buildpack registry if their author has explicitly published them there.

In the case of this buildpack, it's not in the buildpack registry and is deprecated (it's not required given Heroku's multi-buildpack support) so it's unlikely it will ever be published there.

If you need a tarfile/zipfile URL instead of a Git repo URL, you could always use the GitHub archive URLs:
https://github.com/heroku/heroku-buildpack-multi/archive/refs/heads/master.tar.gz
https://github.com/heroku/heroku-buildpack-multi/archive/refs/heads/master.zip

(To find these URLs through the GitHub UI, navigate to the homepage of a repo, click the green "code" button and on the popup there is a "Download zip" link)
